# Generated by Django 4.0.2 on 2022-03-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='porfolioApp/image/')),
                ('git_dir', models.URLField(blank=True, null=True)),
                ('demo_dir', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
